#!/usr/bin/env bash
# Compares supabase/schemas (how the database should look) with what
# supabase/migrations build, and can write the difference as a new migration.
# See README.md.
#
#   supabase/schemas/diff.sh             print the difference; exit 1 if there is one
#   supabase/schemas/diff.sh add_thing   save it as migrations/<timestamp>_add_thing.sql
#
# Needs the local stack running (`supabase start`), but not Docker access: it
# builds two throwaway databases inside the local Postgres, one from the
# migrations and one from the schema files, compares them with the CLI's
# pg-delta engine, and drops them again.
set -euo pipefail

cd "$(dirname "$0")/.."

server=${LOCAL_DB_SERVER:-postgresql://postgres:postgres@127.0.0.1:54322}
schemas=auth,core,attendance,challans
from_db=shadow_from_migrations
to_db=shadow_from_schemas

sql() { psql "$server/$1" -X -q -v ON_ERROR_STOP=1 "${@:2}" > /dev/null; }

cleanup() {
  sql postgres -c "drop database if exists $from_db" -c "drop database if exists $to_db" || true
}
trap cleanup EXIT

# An empty database with just the Supabase pieces our SQL builds on: the
# extensions schema and the auth schema (auth.users, auth.uid(), …). auth is
# copied from the local database, minus our own trigger on auth.users, which
# the migrations and schema files create themselves.
baseline() {
  sql postgres -c "drop database if exists $1" -c "create database $1"
  sql "$1" -c 'create schema extensions' \
    -c 'create extension pgcrypto with schema extensions' \
    -c 'create extension "uuid-ossp" with schema extensions'
  pg_dump "$server/postgres" --schema-only --schema=auth --no-owner --no-privileges \
    | grep -v 'EXECUTE FUNCTION core\.' \
    | sql "$1"
}

baseline $from_db
for file in migrations/*.sql; do sql $from_db -f "$file"; done

baseline $to_db
for file in schemas/*.sql; do sql $to_db -f "$file"; done

difference=$(supabase db diff --use-pg-delta -s "$schemas" \
  --from "$server/$from_db?sslmode=disable" --to "$server/$to_db?sslmode=disable" \
  | sed -n '/^{/,$p' | jq -r .diff)

if [ -z "$difference" ]; then
  echo "Schema files and migrations match."
  exit 0
fi

if [ $# -eq 0 ]; then
  echo "$difference"
  echo
  echo "Schema files and migrations differ (above: what a migration would need to do)." >&2
  exit 1
fi

migration="migrations/$(date -u +%Y%m%d%H%M%S)_$1.sql"
{
  echo "-- Generated by supabase/schemas/diff.sh from the schema files. Read it"
  echo "-- before pushing: renames come out as drop + create, which loses data."
  echo
  echo "$difference"
} > "$migration"
echo "Wrote $migration:"
echo
cat "$migration"
