-- Generated by supabase/schemas/diff.sh from the schema files. Read it
-- before pushing: renames come out as drop + create, which loses data.

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "attendance" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "core" REVOKE ALL ON TABLES FROM "authenticated";

REVOKE ALL ON TABLE "attendance"."shift_defaults" FROM "authenticated";

GRANT INSERT, SELECT ON TABLE "attendance"."shift_defaults" TO "authenticated";

REVOKE ALL ON TABLE "attendance"."status_types" FROM "authenticated";

GRANT INSERT, SELECT, UPDATE ON TABLE "attendance"."status_types" TO "authenticated";

REVOKE ALL ON TABLE "core"."event_types" FROM "authenticated";

GRANT INSERT, SELECT, UPDATE ON TABLE "core"."event_types" TO "authenticated";

REVOKE ALL ON TABLE "core"."modules" FROM "authenticated";

GRANT SELECT ON TABLE "core"."modules" TO "authenticated";

REVOKE ALL ON TABLE "core"."profiles" FROM "authenticated";

GRANT SELECT ON TABLE "core"."profiles" TO "authenticated";

REVOKE ALL ON TABLE "core"."roles" FROM "authenticated";

GRANT SELECT ON TABLE "core"."roles" TO "authenticated";

REVOKE ALL ON TABLE "core"."current_client_addresses" FROM "authenticated";

GRANT SELECT ON TABLE "core"."current_client_addresses" TO "authenticated";

REVOKE ALL ON TABLE "core"."employee_current_status" FROM "authenticated";

GRANT SELECT ON TABLE "core"."employee_current_status" TO "authenticated";

REVOKE ALL ON TABLE "core"."employee_timeline" FROM "authenticated";

GRANT SELECT ON TABLE "core"."employee_timeline" TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "attendance" GRANT SELECT ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "core" GRANT SELECT ON TABLES TO "authenticated";
